### ISSUE TITLE
The browser filled password into id field before it turning into text type

### ISSUE THREAD

**Issue by yc5** [stevenyu113228/NTUST-ID-Is-Not-Password#1]
![Screenshot from 2021-01-25 14-35-40](https://user-images.githubusercontent.com/9305439/105669682-b2e3e400-5f1a-11eb-8f09-e82b816e8be3.png)

**Comment by stevenyu113228** [comment]
修好ㄌ

**Comment by stevenyu113228** [comment]
修好ㄌ
